### ISSUE TITLE
Not able to reproduce any result

### ISSUE THREAD

**Issue by tarun005** [XJTU-XGU/RSDA#2]
Hi, firstly well done on this great work!

I tried out your code on multiple datasets but couldn't achieve the accuracies mentioned in your paper. My numbers are as follows. I have also attached few log-files I get by running your code. Think the very last lines note the accuracy.

Although I agree that absolute numbers change with versions etc, RSDA performing only as good as MSTN in most cases is notable.

**Office-Home**
Clipart - real
MSTN: 71.20
MSTN+RSDA: 71.20
Reported: 76.5

Product - art
MSTN: 63.86
MSTN+RSDA: 66.17
Reported: 67.9

Product - clipart
MSTN: 51.62
MSTN+RSDA: 51.62
Reported: 53

Real-product
MSTN: 81.66
MSTN+RSDA: 83.40
Reported: 85.4

Art - Product
MSTN: 70.24
MSTN+RSDA: 71.14
Reported: 77.7

Product - real
MSTN: 78.61
MSTN+RSDA: 78.61
Reported: 82.0

**visDA2017**

DANN: 64.72
DANN+RSDA: 68.38 
Reported: ~75

**Office-31**
AD - 94.98
Reported - 95.8

DA - 76.39
Reported - 77.4

WA - 77.29
Reported- 78.9

AW - 93.71
Reported - 96.1

Are there any more tricks other than the ones presented in the code you used to achieve the reported accuracies? 

[art_product.txt](https://github.com/XJTU-XGU/RSDA/files/6603411/art_product.txt)
[clipart_real.txt](https://github.com/XJTU-XGU/RSDA/files/6603412/clipart_real.txt)
[product_art.txt](https://github.com/XJTU-XGU/RSDA/files/6603413/product_art.txt)
[visDA_DANN.txt](https://github.com/XJTU-XGU/RSDA/files/6603414/visDA_DANN.txt)
[real_product.txt](https://github.com/XJTU-XGU/RSDA/files/6603415/real_product.txt)

**Comment by XJTU-XGU** [comment]
Thanks. We are checking the code. If there is any problem, we will solve it and re-upload the code.

**Comment by tarun005** [comment]
Thanks for updating the code. I will test these and see if I can repro the new results.
Can you mention what was wrong with previous code and what exactly did you change?

**Comment by XJTU-XGU** [comment]
Firstly, the previous code is for office-31, we released the code for visda and office-home with proper radius and iteration steps. Secondly, the previous code has a few small errors in the calculation of the losses.
