### ISSUE TITLE
Reproduce T-SNE result

### ISSUE THREAD

**Issue by daddyke** [XJTU-XGU/RSDA#3]
Hi,

First of all, thanks for the great work! 

I tried the T-SNE pytorch version but the generated result is different from the one reported in the paper. I am wondering if you can also release the source code of reproducing the T-SNE results .

Thanks for your valuable time and I am looking forward to hearing from you soon!

**Comment by XJTU-XGU** [comment]
Thanks. You may use the tsne code in scikit-learn package.
